---
- name: install cdh5 packages
  yum: name={{ item }} state=present
  with_items:
  - hadoop-hdfs-datanode
  - hadoop-0.20-mapreduce-tasktracker

#- name: copy conf.kya
- copy: src=etc/hadoop/conf.kya dest=/etc/hadoop/
- command: alternatives --install /etc/hadoop/conf hadoop-conf /etc/hadoop/conf.kya 20


- command: ls /tmp/hadoop
  register: result
  ignore_errors: True
- command: rm -rf /tmp/hadoop
  when: result|success
- command: mkdir /tmp/hadoop
- command: chown hdfs. /tmp/hadoop

#- name: hdfs
- command: /etc/init.d/hadoop-hdfs-datanode start
  register: result
  ignore_errors: True
  name: check MASTER NodeName in conf.kya 
  when: result|failed

- command: sudo -uhdfs touch /tmp/test.txt
- command: sudo -uhdfs hadoop fs -mkdir /test
- command: sudo -uhdfs hadoop fs -put /tmp/test.txt /test
- command: sudo -uhdfs hadoop fs -ls -R /

- command: sudo -u hdfs hadoop fs -mkdir /tmp
- command: sudo -u hdfs hadoop fs -chmod -R 1777 /tmp
- command: sudo -u hdfs hadoop fs -mkdir -p /var/lib/hadoop-hdfs/cache/mapred/mapred/staging
- command: sudo -u hdfs hadoop fs -chmod 1777 /var/lib/hadoop-hdfs/cache/mapred/mapred/staging
- command: sudo -u hdfs hadoop fs -chown -R mapred /var/lib/hadoop-hdfs/cache/mapred
- command: sudo -u hdfs hadoop fs -mkdir -p /tmp/hadoop/mapred/system
- command: sudo -u hdfs hadoop fs -chown -R mapred /tmp/hadoop/mapred

- command: mkdir -p /tmp/hadoop/mapred
- command: chown mapred. /tmp/hadoop/mapred

#- name: mapred
- command: /etc/init.d/hadoop-0.20-mapreduce-tasktracker start
  register: result
  ignore_errors: True
  name: check configuration tasktracker in conf.kya 
  when: result|failed
