--- 
- name: install libselinux-python
  yum: name={{ item }} state=present
  with_items:
  - libselinux-python

- name: Selinux Disable
  command: sed -ie "s/^SELINUX=/#SELINUX=/g" /etc/selinux/config

- lineinfile: dest=/etc/selinux/config insertafter=EOF line='SELINUX=disabled'
